server:
  port: 8081
cloud:
  aws:
    credentials:
      profileName:
      instanceProfile: false
    region:
      auto: false
      static: ap-northeast-1
service:
  dns: http://internal-MA-fujishiroms-alb-private-1440693416.ap-northeast-1.elb.amazonaws.com