spring:
  profiles:
    active: dev
cloud:
  aws:
    stack:
      auto: false
server:
  servlet:
    context-path: /backend-for-front
service:
  dns: http://172.17.0.1:8080
  #  http://internal-MA-fujishiroms-alb-private-1440693416.ap-northeast-1.elb.amazonaws.com